name: Build iStore OS 6.x

on:
  repository_dispatch:
  workflow_dispatch:
    # inputs:
      # ssh:
        # description: 'SSH connection to Actions'
        # required: false
        # default: 'false'
  schedule:
   - cron: 0 16 * * *

env:
  REPO_URL: https://github.com/istoreos/istoreos
  # REPO_BRANCH: main
  FEEDS_CONF: feeds.conf
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1-6.x.sh
  DIY_P2_SH: diy-part2-6.x.sh
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        REPO_BRANCH:
          # - main
          - istoreos-24.10
          # - istoreos-23.05
        ARCHITECTURE:
          - armv8
        os:
          - ubuntu-22.04

      fail-fast: false

    steps:
    - name: 合并磁盘
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 100
        root-reserve-mb: 1024

    - name: 准备完成
      uses: actions/checkout@main

    - name: 创建工作目录
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/workdir
        chmod 755 ${GITHUB_WORKSPACE}/workdir
        ls $GITHUB_WORKSPACE
        echo "WORKDIR=$PWD" >> $GITHUB_ENV

    - name: 克隆源码
      working-directory: ${{ env.WORKDIR }}/workdir
      run: |
        df -hT $PWD
        echo "当前路径"$PWD
        echo "当前路径2"$WORKDIR
        ls $GITHUB_WORKSPACE
